#!/bin/bash

# bash_colors

echo "...~/.dotfiles/shell/bash_colors loaded."

# set 256 color profile where possible
if [[ $COLORTERM == gnome-* && $TERM == xterm ]] && infocmp gnome-256color >/dev/null 2>&1; then
    export TERM=gnome-256color
elif infocmp xterm-256color >/dev/null 2>&1; then
    export TERM=xterm-256color
fi

#### CLI Colors (Mac OSX and Free BSC)
export CLICOLOR=1

## ls colors

### Solarized 'ls' colors if we are using Mac OSX `ls`
### as per https://github.com/seebi/dircolors-solarized/issues/10
export LSCOLORS=gxfxbEaEBxxEhEhBaDaCaD

### Same colors for GNU-based ls
### as per http://geoff.greer.fm/lscolors/
export LS_COLORS="di=36;40:ln=35;40:so=31;:pi=0;:ex=1;;40:bd=0;:cd=37;:su=37;:sg=0;:tw=0;:ow=0;:"


### older `ls` colors that looked ok
### export LSCOLORS=Gxfxcxdxbxegedabagacad
### export LS_COLOR="di=1;;40:ln=35;40:so=32;40:pi=33;40:ex=31;40:bd=34;46:cd=34;43:su=0;41:sg=0;46:tw=0;42:ow=0;43:"

## grep colors to highlight matches
export GREP_OPTIONS='--color=auto'

## If Generic Colourizer (GRC) is installed (brew install grc)
## http://kassiopeia.juls.savba.sk/~garabik/software/grc.html
## add colors for make, gcc,g++, as, gas, ld, netstat, ping, traceroute,

  if [ -f "$(brew --prefix)/etc/grc.bashrc" ]; then
    source "$(brew --prefix)/etc/grc.bashrc"
  fi
