#!/bin/bash

# bash_prompt

echo "...~/.dotfiles/shell/bash_prompt loaded."

if [ -f "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh" ];
then
  # gitprompt configuration
  # as per https://github.com/magicmonty/bash-git-prompt
  # colors are defined by .prompt-colors.sh and .git-prompt-colors.sh
  # some other config in .bashrc

  # gitprompt configuration

  # Set config variables first
  GIT_PROMPT_ONLY_IN_REPO=1

  # GIT_PROMPT_FETCH_REMOTE_STATUS=0   # uncomment to avoid fetching remote status

  # GIT_PROMPT_START=...    # uncomment for custom prompt start sequence
  # GIT_PROMPT_END=...      # uncomment for custom prompt end sequence

  # as last entry source the gitprompt script
  # GIT_PROMPT_THEME=Custom # use custom .git-prompt-colors.sh
  # GIT_PROMPT_THEME=Solarized # use theme optimized for solarized color scheme

  source "$(brew --prefix)/opt/bash-git-prompt/share/gitprompt.sh"
else
  # Apple default terminal prompt from /private/etc/bashrc

  PS1='\h:\W \u\$ '
  # Make bash check its window size after a process completes
  shopt -s checkwinsize

  # Tell the terminal about the working directory at each prompt.
  if [ "$TERM_PROGRAM" == "Apple_Terminal" ] && [ -z "$INSIDE_EMACS" ]; then
      update_terminal_cwd() {
          # Identify the directory using a "file:" scheme URL,
          # including the host name to disambiguate local vs.
          # remote connections. Percent-escape spaces.
    local SEARCH=' '
    local REPLACE='%20'
    local PWD_URL="file://$HOSTNAME${PWD//$SEARCH/$REPLACE}"
    printf '\e]7;%s\a' "$PWD_URL"
      }
      PROMPT_COMMAND="update_terminal_cwd; $PROMPT_COMMAND"
  fi
fi
