#!/bin/bash

#find and list processes matching a case-insensitive partial-match string
## as per http://brettterpstra.com/2014/08/15/shell-tricks-a-time-to-kill/

fp () {
	ps Ao pid,comm|awk '{match($0,/[^\/]+$/); print substr($0,RSTART,RLENGTH)": "$1}'|grep -i $1|grep -v grep
}
